# Generated by Django 6.0.6 on 2026-06-11 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cal_target', models.PositiveIntegerField(default=0)),
                ('protein_target', models.PositiveIntegerField(default=0)),
                ('carbs_target', models.PositiveIntegerField(default=0)),
                ('fats_target', models.PositiveIntegerField(default=0)),
                ('fiber_target', models.PositiveIntegerField(default=0)),
                ('cal_total', models.PositiveIntegerField(default=0)),
                ('protein_total', models.PositiveIntegerField(default=0)),
                ('carbs_total', models.PositiveIntegerField(default=0)),
                ('fats_total', models.PositiveIntegerField(default=0)),
                ('fiber_total', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analysed', 'Analysed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('analysis_result', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein_g', models.PositiveIntegerField(default=0)),
                ('carbs_g', models.PositiveIntegerField(default=0)),
                ('fats_g', models.PositiveIntegerField(default=0)),
                ('fiber_g', models.PositiveIntegerField(default=0)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='PlateCheckWeb.dailylog')),
                ('food_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='PlateCheckWeb.foodimage')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('build_muscle', 'Build Muscle'), ('maintain_weight', 'Maintain Weight')], max_length=20)),
                ('diet_type', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian')], max_length=20)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], max_length=20)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
